/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSetting: typeof import('./../components/AppSetting/index.vue')['default']
    Auth: typeof import('./../components/Auth/index.vue')['default']
    HBadge: typeof import('./../ui-kit/HBadge.vue')['default']
    HButton: typeof import('./../ui-kit/HButton.vue')['default']
    HDialog: typeof import('./../ui-kit/HDialog.vue')['default']
    HInput: typeof import('./../ui-kit/HInput.vue')['default']
    HSlideover: typeof import('./../ui-kit/HSlideover.vue')['default']
    HTabList: typeof import('./../ui-kit/HTabList.vue')['default']
    HToggle: typeof import('./../ui-kit/HToggle.vue')['default']
    NotAllowed: typeof import('./../components/NotAllowed/index.vue')['default']
    PageLayout: typeof import('./../components/PageLayout/index.vue')['default']
    PageMain: typeof import('./../components/PageMain/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Trend: typeof import('./../components/Trend/index.vue')['default']
    VanFieldCalendar: typeof import('./../components/VanFieldCalendar/index.vue')['default']
    VanFieldDatePicker: typeof import('./../components/VanFieldDatePicker/index.vue')['default']
    VanFieldPicker: typeof import('./../components/VanFieldPicker/index.vue')['default']
  }
}
